### ISSUE TITLE
frontend pod CrashLoopBackOff(storage-plugin container) with msg="unknown flag: --trace-server-enable"

### ISSUE THREAD

**Issue by calvinxu** [kubewharf/kelemetry#123]
### Steps to reproduce

Deploy following by steps in https://github.com/kubewharf/kelemetry/blob/a832d2856bccdbdedefbe2a437d05c709e22f5bd/docs/DEPLOY.md 

#helm install kelemetry oci://ghcr.io/kubewharf/kelemetry-chart --values values.yaml

### Expected behavior

All pods and svc run up fine and tracing data can be browsed from UI.

### Actual behavior

frontend pod CrashLoopBackOff, check from log
# kubectl logs kelemetry-frontend-75c566859f-mw44x -c storage-plugin
time="2023-07-17T13:59:40Z" level=error msg="unknown flag: --trace-server-enable"

run the docker image, no "--trace-server-enable"" in kelemetry:0.1.0
#docker run -d ghcr.io/kubewharf/kelemetry:0.1.0
af6e0f708046cbae26858de58df97a56442fabe8490646cc0aa61689564ac8d4 
#docker exec -it af6e0f708046cbae26858de58df97a56442fabe8490646cc0aa61689564ac8d4 sh
# kelemetry --help
...
      --span-cache-local-cleanup-frequency duration                          frequency to collect garbage from span cache (default 30m0s)
      --tracer string                                                        implementation of tracer. Possible values are ["otel"]. (default "otel")
      --tracer-otel-endpoint string                                          otel endpoint (default "127.0.0.1:4317")
      --tracer-otel-insecure                                                 allow insecure otel connections
      --tracer-otel-resource-attributes stringToString                       otel resource service attributes (default [service.version=dev])
      --usage string      

As with the frontend failed, not sure if need to switch to  kelemetry:0.2.0? but how about other components, kelemetry-consumer, kelemetry-informers. [tried with 0.2.0, informers pod CrashLoopBackOff with
kubectl logs kelemetry-informers-84c49bc575-hs5dg
time="2023-07-18T01:30:12Z" level=error msg="unknown flag: --diff-cache-use-old-rv"]

and for the kelemetry-collector, already one issue https://github.com/kubewharf/kelemetry/issues/122 for the version 1.42, it does not listen to 4317.  What version shall we use to get the tracing work?

there are also flood of such message in the "kelemetry-collector" pod.
{"level":"info","ts":1689602342.3532155,"caller":"grpc@v1.55.0/server.go:932","msg":"[core][Server #6] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x1b\\\\x01\\\\x00\\\\x01\\\\x17\\\\x03\\\\x03a\\\\x9a\\\\xd36\\\\x81\\\\x87\\\\xba\\\\xb0\\\\xdb\\\\xe8\\\\xdcp\\\\xa9\\\"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1689602359.958463,"caller":"grpc@v1.55.0/server.go:932","msg":"[core][Server #6] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x1b\\\\x01\\\\x00\\\\x01\\\\x17\\\\x03\\\\x03c\\\\uf448\\\\xb2$\\\\xf7\\\\x02\\\\x1f\\\\xee\\\\x13\\\\xe9\\\\x87\\\"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1689602562.2759514,"caller":"grpc@v1.55.0/server.go:932","msg":"[core][Server #6] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x1b\\\\x01\\\\x00\\\\x01\\\\x17\\\\x03\\\\x03Z\\\\xfb\\\\x05A=0\\\\xb0mi\\\\x12\\\\x1a\\\\xfa\\\\xd6\\\"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1689602634.1497142,"caller":"grpc@v1.55.0/server.go:932","msg":"[core][Server #6] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x1b\\\\x01\\\\x00\\\\x01\\\\x17\\\\x03\\\\x03PO\\\\xb9#%W־\\\\x03\\\\x1a\\\\xac\\\\t\\\\x9a\\\"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1689602778.7651076,"caller":"grpc@v1.55.0/server.go:932","msg":"[core][Server #6] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x1b\\\\x01\\\\x00\\\\x01\\\\x17\\\\x03\\\\x03e\\\\xd6z4\\\\xccLq\\\\xb286\\\\xb4\\\\x02z\\\"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1689602918.8066566,"caller":"grpc@v1.55.0/server.go:932","msg":"[core][Server #6] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x1b\\\\x01\\\\x00\\\\x01\\\\x17\\\\x03\\\\x03\\\\xb7\\\\x98\\\\xea\\\\xe3\\\\xd0\\\\x12\\\\xb2@\\\\xe7\\\\xc7S\\\\xe0\\\\x19\\\"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1689602953.5312855,"caller":"grpc@v1.55.0/server.go:932","msg":"[core][Server #6] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x1b\\\\x01\\\\x00\\\\x01\\\\x17\\\\x03\\\\x03K\\\\x15\\\\x01\\\\xf9\\\\x1cϋ\\\\xfb\\\\xc6xr7\\\\xe2\\\"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1689603063.8368163,"caller":"grpc@v1.55.0/server.go:932","msg":"[core][Server #6] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x1b\\\\x01\\\\x00\\\\x01\\\\x17\\\\x03\\\\x03\\\\xa9J\\\\x9bȨު\\\\xa8\\\\xb6\\\\x1bP\\\\xca\\\\xee\\\"\"","system":"grpc","grpc_log":true}

### Kelemetry version

0.1.0

### Environment

Kubernetes version :1.24.15
Jaeger version: 1.4.2

**Comment by SOF3** [comment]
Hi, please use version 0.2.0 instead.

**Comment by calvinxu** [comment]
Already tried 0.2.0, kubectl logs kelemetry-informers-84c49bc575-hs5dg
time="2023-07-18T01:30:12Z" level=error msg="unknown flag: --diff-cache-use-old-rv"], manually disable this flag, though the pods are up and running. flood of message "...Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams received bogus greeting from client.." in the "kelemetry-collector" pod as showed as above.

**Comment by noovertime7** [comment]
我也遇到了这个错误，当替换为0.2.0时，kelemetry-informer报错time="2023-07-18T13:05:58Z" level=error msg="unknown flag: --diff-cache-use-old-rv"
