### ISSUE TITLE
how to configure the storageBackend to use elasticsearch

### ISSUE THREAD

**Issue by Felix-YuJing** [kubewharf/kelemetry#151]
### Description

I want to aggregate multicluster event by kelemetry  as mentioned in #136  
but I confused how to configure the storageBackend to use elasticsearch. I met errors when I set `storageBackend.type` to `elasticsearch`(I'm using kelemetry-chart-0.2.2): 

> Error: UPGRADE FAILED: template: kelemetry-chart/templates/frontend.deployment.yaml:57:15: executing "kelemetry-chart/templates/frontend.deployment.yaml" at <include "kelemetry.storage-plugin-options" .>: error calling include: template: kelemetry-chart/templates/_helpers.yaml:263:4: executing "kelemetry.storage-plugin-options" at <include "kelemetry.storage-plugin-options-raw" .>: error calling include: template: kelemetry-chart/templates/_helpers.yaml:276:27: executing "kelemetry.storage-plugin-options-raw" at <include "kelemetry.storage-options-raw" .>: error calling include: template: kelemetry-chart/templates/_helpers.yaml:299:4: executing "kelemetry.storage-options-raw" at <include "kelemetry.storage-options-raw-stateless" .>: error calling include: template: no template "kelemetry.storage-options-raw-stateless" associated with template "gotpl"

Is there any example about it?

**Comment by SOF3** [comment]
Fixed in #132, please use v0.2.3 of the chart.
