### ISSUE TITLE
Deploy using helm chart failed

### ISSUE THREAD

**Issue by calvinxu** [kubewharf/kelemetry#154]
### Steps to reproduce

helm install kelemetry oci://ghcr.io/kubewharf/kelemetry-chart --values values.yaml

### Expected behavior

install successfully

### Actual behavior

#helm install kelemetry oci://ghcr.io/kubewharf/kelemetry-chart --values values.yaml

Pulled: ghcr.io/kubewharf/kelemetry-chart:0.2.3
Digest: sha256:5c6ae9ee1e30fc8f5f2409db3a5cfa502b0dabf8c42fba3e122e420317f5e89a
Error: INSTALLATION FAILED: template: kelemetry-chart/templates/storage.deployment.yaml:30:16: executing "kelemetry-chart/templates/storage.deployment.yaml" at <include "kelemetry.storage-options-stateless" .>: error calling include: template: no template "kelemetry.storage-options-stateless" associated with template "gotpl"

### Kelemetry version

0.2.3

### Environment

k8s:1.2.4
Jaeger:1.42

**Comment by SOF3** [comment]
fixed in v0.2.4
