### ISSUE TITLE
jaeger UI Service count is 8

### ISSUE THREAD

**Issue by luojianlong** [kubewharf/kelemetry#179]
### Steps to reproduce

jaeger UI Service count is 8

**Comment by SOF3** [comment]
Service count is expected to be 8 in 0.2.4, what is the problem?

**Comment by luojianlong** [comment]
> Service count is expected to be 8 in 0.2.4

正常service 列表有30多个

**Comment by SOF3** [comment]
Oh sorry, there was some miscommunication here. Service count of 8 is normal for the default configuration in 0.2.4, and the operation count is the number of clusters you have; the one with 32 services you saw was under a special configuration that enabled extension traces, which is normally unused.

Having 8 services is normal; however, it is abnormal if you can't search any traces there. Consider checking the health of kelemetry-collector and kelemetry-remote-storage, and maybe check if you configured the audit webhook correctly.
