### ISSUE TITLE
The kelemetry-chart v0.2.7 is unavailable on kubernetes v1.21.3

### ISSUE THREAD

**Issue by Czoyx** [kubewharf/kelemetry#347]
### Steps to reproduce

1. Download [values.yaml](https://github.com/kubewharf/kelemetry/blob/main/charts/kelemetry/values.yaml) and configure the settings(I only changed storageClassName).
3. Install the chart:  `helm install kelemetry oci://ghcr.io/kubewharf/kelemetry-chart --version v0.2.7  --values values.yaml`
4. Output:
```
Pulled: ghcr.io/kubewharf/kelemetry-chart:v0.2.7
Digest: sha256:ae6acb3d014a5de5ff7f498fe5bcddc5b9da05122269704ad303eac888798122
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec
```
5. Then I  configure the field "io.k8s.api.apps.v1.StatefulSetSpec.serviceName", ` helm install` again, the comsumers and informers CrashLoopBackOff, even after the etcds is Running.
Log:
```
time="2024-09-03T06:04:46Z" level=error msg="unknown flag: --aggregator-span-follow-ttl"
```

### Actual behavior

1. Although the latest version of k8s does not have this problem, according to the [documentation]( https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/stateful-set-v1/#StatefulSetSpec), I think this field "io.k8s.api.apps.v1.StatefulSetSpec.serviceName" should be configured.
2. The comsumers and informers CrashLoopBackOff also occurs in the latest version of kind cluster.

### Kelemetry version

v0.2.7

### Environment

kubernetes v1.21.3

**Comment by SOF3** [comment]
Right, the `aggregator-span-follow-ttl` option has been removed a long time ago, we forgot to update the chart for that.
